spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    # url: 'jdbc:h2:mem:test' # 인메모리 모드를 위한 URL입니다.
    # url: 'jdbc:h2:~/test'   # 임베디드 모드를 위한 URL입니다.
    # DB_CLOSE_DELAY=-1       # 데이터베이스가 닫히지 않도록 설정합니다. 연결이 끊어졌을 때도 유지됩니다.
    # DB_CLOSE_ON_EXIT=FALSE  # 애플리케이션 종료 시 데이터베이스를 닫지 않도록 설정합니다.
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
#        default_read_only: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  logging:
    level:
      org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/hhplus"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  logging:
    level:
      org.hibernate.orm.jdbc.bind: trace